simulation_time: 10
warm_up_time: 0
server_side:
    n_projects: 2
    sprojects:
      - snumber: 0
        name: ATLAS@home
        nscheduling_servers: 1
        ndata_servers: 1
        ndata_client_servers: 1
        server_pw: 12000000000f
        disk_bw: 167772160
        ifgl_percentage: 100
        ifcd_percentage: 100
        averagewpif: 1
        input_file_size: 1024
        task_fpops: 100000000000
        output_file_size: 11000
        min_quorum: 1
        target_nresults: 1
        max_error_results: 8
        max_total_results: 10
        max_success_results: 8
        delay_bound: 14400
        success_percentage: 98
        canonical_percentage: 90
        output_file_storage: 0
        dsreplication: 1
        dcreplication: 1
      - snumber: 1
        name: ATLAS2@home
        nscheduling_servers: 1
        ndata_servers: 1
        ndata_client_servers: 1
        server_pw: 12000000000f
        disk_bw: 167772160
        ifgl_percentage: 100
        ifcd_percentage: 100
        averagewpif: 1
        input_file_size: 1024
        task_fpops: 2000000000
        output_file_size: 11000
        min_quorum: 1
        target_nresults: 1
        max_error_results: 8
        max_total_results: 10
        max_success_results: 8
        delay_bound: 64800
        success_percentage: 98
        canonical_percentage: 90
        output_file_storage: 0
        dsreplication: 1
        dcreplication: 1
client_side:
    n_groups: 1
    groups:
      - n_clients: 700
        ndata_clients: 350
        connection_interval: 60
        scheduling_interval: 3600
        gbw: 50Mbps
        glatency: 7.3ms
        traces_file: /Traces/lhc/unsorted
        max_speed: 117.71
        min_speed: 0.07
        pv_distri: 5
        pa_param: 0.0534
        pb_param: -1
        db_distri: 2
        da_param: 21.086878916910564
        db_param: 159.1597190181666
        av_distri: 5
        aa_param: 0.095
        ab_param: -1
        nv_distri: 5
        na_param: 0.24
        nb_param: -1
        att_projs: 2
        gprojects:
          - pnumber: 0
            priority: 10
            lsbw: 10Gbps
            lslatency: 50us
            ldbw: 2Mbps
            ldlatency: 50us
          - pnumber: 1
            priority: 1
            lsbw: 10Gbps
            lslatency: 50us
            ldbw: 2Mbps
            ldlatency: 50us
